[package]
name = "neos_peeps"
version = "0.0.0-alpha.1"
edition = "2021"
authors = ["ljoonal"]
description = "An application to view your neos friends."
repository = "https://git.ljoonal.xyz/ljoonal/NeosPeeps"

# https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neos = "0.0.0-alpha.1"

eframe = { version = "0.16.0", default-features = false, features = [
	"egui_glow",
	"persistence",
] }
minreq = { version = "2.4.2", features = [
	"https-rustls-probe",
	"json-using-serde",
] }

serde = "1"
serde_json = "1"

rand = { version = "0.8" }
chrono = "0.4.19"

[dependencies.image]
version = "0.23.14"
default-features = false

features = ["bmp", "png", "hdr", "tiff", "jpeg", "jpeg_rayon", "tga", "gif"]

[patch.crates-io]

#neos = { path = "../neos_rs/" }

# If you want to use the bleeding edge version of `egui`:
# eframe = { git = "https://github.com/emilk/egui", branch = "master" }

# If you fork https://github.com/emilk/egui you can test with:
# eframe = { path = "../egui/eframe" }
